version: '2'

networks:
  back:
    driver: bridge

services:
  db:
    restart: always
    image: mysql:5.6
    volumes:
      - ./billing/mysql:/var/lib/mysql
    env_file:
      - system.env
      - mysql.env
    networks:
      back:
        aliases:
          - bill_db
  core:
    image: blackojack/lanbilling:core
    restart: always
    depends_on:
      - db
    volumes:
      - ./billing/conf:/root/billing/conf
      - ./billing/logs:/root/billing/logs
      - ./billing/www:/var/www/html
    env_file:
      - system.env
      - mysql.env
      - lbcore.env
    networks:
      back:
        aliases:
          - soap
    ports:
      - "34012:34012"
  web:
    image: blackojack/lanbilling:web
    restart: always
    depends_on:
      - core
    volumes:
      - ./billing/www:/usr/local/apache2/htdocs
    env_file:
      - system.env
    networks:
      - back
    ports:
      - "80:80"