version: '2'

networks:
  back:
    driver: bridge

services:
  db:
    restart: always
    image: mysql:5.6
    volumes:
      - ../lbcore_data/billing/mysql:/var/lib/mysql
    env_file:
      - system.env
      - mysql.env
    networks:
      back:
        aliases:
          - bill_db
  core:
    build: ./core
    restart: always
    depends_on:
      - db
    volumes:
      - ../lbcore_data/billing/conf:/root/billing/conf
      - ../lbcore_data/billing/www:/var/www/html
    env_file:
      - system.env
      - mysql.env
      - lbcore.env
    networks:
      back:
        aliases:
          - soap
    ports:
      - "34012:34012"
  web:
    build: ./web
    restart: always
    depends_on:
      - core
    volumes:
      - ../lbcore_data/billing/www:/usr/local/apache2/htdocs
    env_file:
      - system.env
    networks:
      - back
    ports:
      - "8088:80"